/*
Main code of QSearch, which searches for vectors that have the same first 3d/2 columns of their G-matrix.

Written by:     Joseph Farah
Last updated:   Sep 29 2018
*/


#include <iostream>
#include <vector>
#include <cstdlib>

void getMatrix(int dimension) {
    /* Get a G matrix as generated by the included Mathematica notebook */

    std::system("python generate_table.py " << dimension);
}

int main() {
    return 0;
}